# Generated by Django 4.0.2 on 2022-04-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_description',
            field=models.TextField(null=True),
        ),
    ]
